# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

# Create a list of jobs
jobs:
  # Name the first job "print_hello"
  print_hello:
    # Use docker image for Node.js
    docker:
      - image: circleci/node:13.8.0
    # Add step to print Hello
    steps:
      - run: echo "Hello"
  
  # Name the second job "print_name"
  print_name:
    # Use docker image for Node.js
    docker:
      - image: circleci/node:13.8.0
    # Add step to print World
    steps:
      # Set environment variable MY_NAME
      - run: echo 'export MY_NAME="Sakshi Kulshreshtha"' >> $BASH_ENV |
      # Project level env variable is redacted and hidden
      echo $myName |
      # Env variable not declared in Project / Context level in CircleCI is not hidden.
      # Also note that env variable can be with or without curly braces {}
      echo ${MY_NAME}

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the 3 jobs
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          # Add a prerequisite step for print_world
          requires: [print_hello]
