# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

# Create a list of jobs
jobs:
  # Name the first job "print_hello"
  print_hello:
    # Use docker image for Node.js
    docker:
      - image: circleci/node:13.8.0
    # Add step to print Hello
    steps:
      - run: echo "Hello"
  
  # Name the second job "print_name"
  print_name:
    # Use docker image for Node.js
    docker:
      - image: circleci/node:13.8.0
    # Add step to print Hello and fetch my name from env variable
    steps:
      - run: echo "Hello" $myName
      
  # Name the third job "print_name"
  save_output:
    # Use docker image for Node.js
    docker:
      - image: circleci/node:13.8.0
    
    # Add step to save Hello Sakshi in a txt file
    steps:
      - run: echo "Hello Sakshi" > /tmp/output.txt
      # Persist txt file to workspace
      - persist_to_workspace:
          root: /tmp
          paths:
            - output.txt
  
  # Name the fourth job "print_output"
  print_output:
    # Use docker image for Node.js
    docker:
      - image: circleci/node:13.8.0
      
    steps:
      # Attach workspace to fetch txt file
      - attach_workspace:
          at: /tmp
      # Print contents of txt file
      - run: cat output.txt

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the jobs
    jobs:
      - welcome/run
      - print_hello
      - print_name
      - save_output
      - print_output:
          # Add a prerequisite step for print_output
          requires: [save_output]
